Repository Netcracker/qubership-colly, pull requests merged in 2025-03, with the labels that each got.

#15 feat: Add an ability to store data from clusters in Database
  pom.xml
  src/main/java/org/qubership/colly/ClusterResourcesLoader.java
  src/main/java/org/qubership/colly/ClusterResourcesRest.java
  src/main/java/org/qubership/colly/CollyStorage.java
  src/main/java/org/qubership/colly/EnvironmentsLoader.java
  src/main/java/org/qubership/colly/data/Cluster.java
  src/main/java/org/qubership/colly/data/ClusterDto.java
  src/main/java/org/qubership/colly/data/ConfigMap.java
  src/main/java/org/qubership/colly/data/ConfigMapDto.java
  src/main/java/org/qubership/colly/data/Deployment.java
  src/main/java/org/qubership/colly/data/DeploymentDto.java
  src/main/java/org/qubership/colly/data/Environment.java
  src/main/java/org/qubership/colly/data/Namespace.java
  src/main/java/org/qubership/colly/data/NamespaceDto.java
  src/main/java/org/qubership/colly/db/Cluster.java
  src/main/java/org/qubership/colly/db/ConfigMap.java
  src/main/java/org/qubership/colly/db/Deployment.java
  src/main/java/org/qubership/colly/db/Namespace.java
  src/main/java/org/qubership/colly/db/Pod.java
  src/main/java/org/qubership/colly/storage/ClusterRepository.java
  src/main/java/org/qubership/colly/storage/DeploymentRepository.java
  src/main/java/org/qubership/colly/storage/NamespaceRepository.java
  src/main/resources/application.properties
  src/test/resources/kubeconfigs/test-cluster
Labels: bug, enhancement, refactor

#16 feat: Simple UI for visualisation environments list
  pom.xml
  src/main/java/org/qubership/colly/IndexController.java
  src/main/resources/META-INF/resources/style.css
  src/main/resources/templates/index.html
Labels: enhancement

#19 refactor: Update README.md
  README.md
Labels: refactor

#20 ci: update of common workflows
  .editorconfig
  .gitattributes
  .github/auto-labeler-config.yaml
  .github/linters/.checkov.yaml
  .github/linters/.eslintrc.yml
  .github/linters/.flake8
  .github/linters/.golangci.yml
  .github/linters/.jscpd.json
  .github/linters/.yaml-lint.yml
  .github/linters/actionlint.yml
  .github/release-drafter-config.yml
  .github/super-linter.env
  .github/workflows/automatic-pr-labeler.yaml
  .github/workflows/cdxgen.yaml
  .github/workflows/cla.yaml
  .github/workflows/pr-collect-commit-messages.yaml
  .github/workflows/pr-conventional-commits.yaml
  .github/workflows/pr-lint-title.yaml
  .github/workflows/profanity-filter.yaml
Labels: enhancement

#22 refactor: remove unsued config for TS, Go. remove prettier
  .github/linters/.eslintrc.yml
  .github/linters/.golangci.yml
  .github/workflows/prettier.yaml
Labels: refactor

#25 fix: Delete .github/workflows/cdxgen.yaml
  .github/workflows/cdxgen.yaml
Labels: bug

#29 feat: add an ability to load data from clusters by CloudPassport. Closes #3
  README.md
  pom.xml
  src/main/java/org/qubership/colly/CloudPassportLoader.java
  src/main/java/org/qubership/colly/ClusterResourcesLoader.java
  src/main/java/org/qubership/colly/CollyStorage.java
  src/main/java/org/qubership/colly/EnvironmentsLoader.java
  src/main/java/org/qubership/colly/KubeConfigLoader.java
  src/main/java/org/qubership/colly/data/CloudData.java
  src/main/java/org/qubership/colly/data/CloudPassport.java
  src/main/java/org/qubership/colly/data/CloudPassportData.java
  src/main/resources/application.properties
  src/main/resources/templates/index.html
  src/test/resources/clusters/empty-folder/.gitkeep
  src/test/resources/clusters/test-cluster/cloud-passport/test-cluster-creds.yml
  src/test/resources/clusters/test-cluster/cloud-passport/test-cluster.yml
  src/test/resources/kubeconfigs/test-cluster
Labels: bug, enhancement, refactor

#30 feat: build docker image
  .github/metadata-config.yml
  .github/workflows/build-project.yaml
  Dockerfile
Labels: enhancement

#32 bugfix/fix-docker-build
  .github/workflows/build-project.yaml
Labels: bug
