Repository Netcracker/qubership-colly, pull requests merged in 2025-05, with the labels that each got.

#46 feat: Load environments from Cloud Passport
  README.md
  pom.xml
  src/main/java/org/qubership/colly/CloudPassportLoader.java
  src/main/java/org/qubership/colly/ClusterResourcesLoader.java
  src/main/java/org/qubership/colly/CollyStorage.java
  src/main/java/org/qubership/colly/GitService.java
  src/main/java/org/qubership/colly/cloudpassport/CloudPassport.java
  src/main/java/org/qubership/colly/cloudpassport/CloudPassportEnvironment.java
  src/main/java/org/qubership/colly/cloudpassport/CloudPassportNamespace.java
  src/main/java/org/qubership/colly/cloudpassport/envgen/CloudData.java
  src/main/java/org/qubership/colly/cloudpassport/envgen/CloudPassportData.java
  src/main/java/org/qubership/colly/cloudpassport/envgen/EnvDefinition.java
  src/main/java/org/qubership/colly/cloudpassport/envgen/Inventory.java
  src/main/java/org/qubership/colly/cloudpassport/envgen/Namespace.java
  src/main/java/org/qubership/colly/data/CloudPassport.java
  src/main/java/org/qubership/colly/data/ClusterDto.java
  src/main/java/org/qubership/colly/data/ConfigMapDto.java
  src/main/java/org/qubership/colly/data/DeploymentDto.java
  src/main/java/org/qubership/colly/data/Environment.java
  src/main/java/org/qubership/colly/data/NamespaceDto.java
  src/main/java/org/qubership/colly/data/Pod.java
  src/main/resources/application.properties
  src/test/java/org/qubership/colly/CloudPassportLoaderTest.java
  src/test/java/org/qubership/colly/ClusterResourcesLoaderTest.java
  src/test/resources/gitrepo_with_cloudpassports/empty-folder/.gitkeep
  src/test/resources/gitrepo_with_cloudpassports/test-cluster/cloud-passport/test-cluster-creds.yml
  src/test/resources/gitrepo_with_cloudpassports/test-cluster/cloud-passport/test-cluster.yml
  src/test/resources/gitrepo_with_cloudpassports/test-cluster/env-test/Inventory/env_definition.yml
  src/test/resources/gitrepo_with_cloudpassports/test-cluster/env-test/Namespaces/bss/namespace.yml
Labels: bug, documentation, enhancement, refactor

#48 feat: Support cloning multiple Git repositories with cloud passports
  README.md
  src/main/java/org/qubership/colly/CloudPassportLoader.java
  src/main/resources/application.properties
Labels: enhancement

#50 Fix: correct condition for git repository cloning
  src/main/java/org/qubership/colly/CloudPassportLoader.java
  src/main/resources/application.properties
Labels: bug

#51 feat: Support environment type detection via namespace labels
  README.md
  img.png
  src/main/java/org/qubership/colly/ClusterResourcesLoader.java
  src/main/java/org/qubership/colly/db/EnvironmentType.java
  src/main/webui/src/entities/environments.ts
  src/test/java/org/qubership/colly/CloudPassportLoaderTest.java
  src/test/java/org/qubership/colly/ClusterResourcesLoaderTest.java
  src/test/resources/gitrepo_with_cloudpassports/test-cluster/env-test/Namespaces/bss/namespace.yml
Labels: bug, documentation, enhancement

#52 feat: Add Helm charts and prepare release
  .github/assets-config.yaml
  .github/helm-chart-release-config.yaml
  .github/metadata-action-config.yml
  .github/release-drafter-config.yml
  .github/workflows/release.yaml
  charts/qubership-colly/Chart.yaml
  charts/qubership-colly/templates/deployment.yaml
  charts/qubership-colly/templates/ingress.yaml
  charts/qubership-colly/templates/secret.yaml
  charts/qubership-colly/templates/service.yaml
  charts/qubership-colly/values.yaml
Labels: bug, enhancement

#53 refactor: Add Helm instructions and refactor release setup
  .github/workflows/release.yaml
  README.md
  charts/qubership-colly/Chart.yaml
  charts/qubership-colly/templates/deployment.yaml
  charts/qubership-colly/templates/ingress.yaml
  charts/qubership-colly/templates/secret.yaml
  charts/qubership-colly/templates/service.yaml
  charts/qubership-colly/values.yaml
Labels: bug, documentation, refactor

#56 chore: update of common workflows
  .github/workflows/cla.yaml
  .github/workflows/link-checker.yaml
  .github/workflows/pr-lint-title.yaml
  .github/workflows/profanity-filter.yaml
  CONTRIBUTING.md
  src/main/resources/application.properties
Labels: refactor

#62 feat: add Team column for environment. #61
  src/main/java/org/qubership/colly/ClusterResourcesRest.java
  src/main/java/org/qubership/colly/CollyStorage.java
  src/main/java/org/qubership/colly/db/Environment.java
  src/main/webui/src/EnvTable.tsx
  src/main/webui/src/components/EditEnvironmentDialog.tsx
  src/main/webui/src/entities/environments.ts
Labels: enhancement
